package com.vainaweb.escolavainaweb.enums;

public enum Curso {
	ADMINISTAÇÃO,
	ENGENHARIA_DA_COMPUTAÇÃO,
	SISTEMAS_DE_INFORMAÇÃO,
	ANALISE_DESENVOLVIMENTO_DE_SISTEMAS,
	CIENCIA_DA_COMPUTAÇÃO,
	MEDICINA,
	ENFERMAGEM,
	FARMACIA,
	ENGENHARIA_DE_SOFTWARE,
	GESTAO_DA_TI,
	REDES_DE_COMPUTADORES,
	AGRONOMIA,
	GESTÃO_AMBIENTAL
}
